# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tether < Formula
  desc "Open URLs requested on a headless server in a browser on your desktop, over SSH."
  homepage "https://github.com/mwdomino/tether"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mwdomino/tether/releases/download/v0.3.0/tether_0.3.0_darwin_amd64.tar.gz"
      sha256 "a31044f8b87ead366b044a2ff16cb72978b6e53d6d3d1251842741dc1e7995f7"

      define_method(:install) do
        bin.install "tether"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mwdomino/tether/releases/download/v0.3.0/tether_0.3.0_darwin_arm64.tar.gz"
      sha256 "a0cf4e1711fa9a8bdd705e786679f49a97267d2479285985ad1da20f831ad13b"

      define_method(:install) do
        bin.install "tether"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mwdomino/tether/releases/download/v0.3.0/tether_0.3.0_linux_amd64.tar.gz"
      sha256 "dfca29892ea5fe0f7c77d365ed45f81d5b5e781e36845ac9ad37f96576631975"
      define_method(:install) do
        bin.install "tether"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mwdomino/tether/releases/download/v0.3.0/tether_0.3.0_linux_arm64.tar.gz"
      sha256 "c8e522e5890025951289b2e11dca1b5766823797d59fa6990dea80a22f0d39da"
      define_method(:install) do
        bin.install "tether"
      end
    end
  end

  test do
    system "#{bin}/tether", "--version"
  end
end
