# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tether < Formula
  desc "Open URLs requested on a headless server in a browser on your desktop, over SSH."
  homepage "https://github.com/mwdomino/tether"
  version "0.5.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mwdomino/tether/releases/download/v0.5.2/tether_0.5.2_darwin_amd64.tar.gz"
      sha256 "ac857e40c11013fbff35c02fc7fcf24aaa103a58e5a7bdce06a8e32bcd935872"

      define_method(:install) do
        bin.install "tether"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mwdomino/tether/releases/download/v0.5.2/tether_0.5.2_darwin_arm64.tar.gz"
      sha256 "0137428e53d0e0785c1a71e10ba5ca5d7c56ac966f663166e09f7a96532b8c32"

      define_method(:install) do
        bin.install "tether"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mwdomino/tether/releases/download/v0.5.2/tether_0.5.2_linux_amd64.tar.gz"
      sha256 "db120c4a96165746ee5c5640b0eab27f7ab1def6c639db6e7267f8a97ee55120"
      define_method(:install) do
        bin.install "tether"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mwdomino/tether/releases/download/v0.5.2/tether_0.5.2_linux_arm64.tar.gz"
      sha256 "9df0948fd3e1a73549350e74c902a5a0bf823360754a8713150919130b0fef9d"
      define_method(:install) do
        bin.install "tether"
      end
    end
  end

  test do
    system "#{bin}/tether", "--version"
  end
end
