# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tether < Formula
  desc "Open URLs requested on a headless server in a browser on your desktop, over SSH."
  homepage "https://github.com/mwdomino/tether"
  version "0.5.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mwdomino/tether/releases/download/v0.5.4/tether_0.5.4_darwin_amd64.tar.gz"
      sha256 "5f17576f5197ce03088324c5ffd2c4b52dbda8b44bdb4b3bc488d5ef6b223b51"

      define_method(:install) do
        bin.install "tether"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mwdomino/tether/releases/download/v0.5.4/tether_0.5.4_darwin_arm64.tar.gz"
      sha256 "8602c8de9affcf6e723caa834c9c4b9d4ed6d141dbf91609e5932dce8ed47a30"

      define_method(:install) do
        bin.install "tether"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mwdomino/tether/releases/download/v0.5.4/tether_0.5.4_linux_amd64.tar.gz"
      sha256 "c316c509705778399fffdc65dc384acc890448eb260b3de5b0087fe72e97d547"
      define_method(:install) do
        bin.install "tether"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mwdomino/tether/releases/download/v0.5.4/tether_0.5.4_linux_arm64.tar.gz"
      sha256 "c41237098eb28bd1dc38bb9852a7ef2c0e5621c3ba378ddbbf59f707d0453ee1"
      define_method(:install) do
        bin.install "tether"
      end
    end
  end

  test do
    system "#{bin}/tether", "--version"
  end
end
